
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
          ports:
            - containerPort: 9200
          resources:
            limits:
              cpu: "2"
              memory: 2048Mi
            requests:
              cpu: "0.1"
              memory: 512Mi
          env:
            - name: discovery.type
              value: single-node

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.11.3
          ports:
            - containerPort: 5601
          resources:
            limits:
              cpu: "1"
              memory: 2048Mi
            requests:
              cpu: "0.1"
              memory: 1024Mi
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200

---

apiVersion: v1
kind: Service
metadata:
  name: kibana
  
spec:
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: kibana