apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: probe
  labels:
    app: k8s-combat-service # 通过标签选择关联
  name: k8s-combat-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-combat-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-combat-service
    spec:
      containers:
        - name: k8s-combat-service
          image: crossoverjie/k8s-combat:v1
          imagePullPolicy: Always
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /ping
              port: 8081
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8081
              scheme: HTTP
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8081
              scheme: HTTP
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 100Mi
            requests:
              cpu: "0.1"
              memory: 10Mi
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-combat-service
  namespace: probe
spec:
  selector:
    app: k8s-combat-service # 通过标签选择关联
  type: ClusterIP
  ports:
    - port: 8081        # 本 Service 的端口
      targetPort: 8081  # 容器端口
      name: app