apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-combat
  name: k8s-combat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-combat
  template:
    metadata:
      labels:
        app: k8s-combat
    spec:
      containers:
        - name: k8s-combat
          image: crossoverjie/k8s-combat:v1
          imagePullPolicy: Always
          volumeMounts:
            - name: app
              mountPath: "/go/bin/app.yaml"
              subPath: APP
          envFrom:
            - configMapRef:
                name: k8s-combat-configmap
            - secretMapRef:
                name: k8s-combat-secret
          resources:
            limits:
              cpu: "1"
              memory: 300Mi
            requests:
              cpu: "0.1"
              memory: 100Mi
      volumes:
        - name: app
          configMap:
            name: k8s-combat-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-combat-configmap
data:
  PG_URL: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
  APP: |
    name: k8s-combat
    pulsar:
      url: "pulsar://localhost:6650"
      token: "abc"

---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-combat-secret
type: Opaque
data:
  PWD: YWJjCg==
