apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingress-gateway
  namespace: default
spec:
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - 'www.service1.io'
  selector:
    app: istio-ingressgateway #与现有的 gateway 关联
    istio: ingressgateway

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: k8s-combat-istio-http-vs
spec:
  gateways:
    - istio-ingress-gateway
  hosts:
    - www.service1.io
  # match version to other version
  http:
#    - name: v1
#      match:
#        - headers:
#            version:
#              exact: '100'
#      route:
#        - destination:
#            host: k8s-combat-service-istio-mesh
#            subset: v1
#    - name: v2
#      match:
#        - headers:
#            version:
#              exact: '200'
#      route:
#        - destination:
#            host: k8s-combat-service-istio-mesh
#            subset: v2
    - name: default
      route:
        - destination:
            host: k8s-combat-service-istio-mesh
            port:
              number: 8081
            subset: v1